name: Sync With Hugging Face Space

on:
  push:
    branches: [ main ]   # or your branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync to Space
        uses: alex-bene/huggingface-space-sync-action@v0.1
        with:
          github_repo_id: Aadi070201/Battery_app          # <== your GitHub repo
          github_branch: main
          huggingface_repo_id: Aadi070201/battery_detect  # <== your Space
          hf_username: Aadi070201
          hf_token: ${{ secrets.HF_TOKEN }}
          yaml_header_path: .github/hf_readme_header.md   # YAML front matter file
