name: Sync With Hugging Face Space

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  push-to-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history (unshallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       # <-- IMPORTANT: full history
          lfs: false           # avoid LFS smudge; we don't need it for code

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to Space main (force overwrite)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SPACE: Aadi070201/battery_detect
        run: |
          # Optional: fetch the Space branch first; ignore failure if it doesn't exist
          git remote add space https://oauth2:${HF_TOKEN}@huggingface.co/spaces/${SPACE}
          git fetch space main || true
          # Force push current commit to Space main
          git push space HEAD:main --force
